theme: jekyll-theme-cayman
title: Plotly-Belly-Botton-Biodiversity
description: Small project to document some kind of bactiria and especially the ones that have the ability in synthesize protiens that taste like beef
